version: '3.4'
services:
    mysql_test:
        image: mysql:8.0.28
        container_name: mysql_test
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=mysql_test_db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - "3306:3306"
        volumes:
            - ./initdb.d:/docker-entrypoint-initdb.d